### ISSUE TITLE
Adblocking not working on apps in iphone and barely blocks anything since reducing the size from 490k+ to 480k+ .

### ISSUE THREAD

**Issue by Domsicols** [Lennolium/PrivacyShield#11]
I tested on https://d3ward.github.io/toolz/adblock.html and my score was 57% currently using the gold version with adguard pro on ios.

**Comment by zer09** [comment]
Also https://d3ward.github.io/toolz/adblock.html is bloked on diamond version.
![Screenshot_20220710_160830](https://user-images.githubusercontent.com/780780/178136740-da2f835f-83d5-4b4e-82d5-2740a316e333.png)

**Comment by Lennolium** [comment]
Fixed in upcoming version :)
