### ISSUE TITLE
Is the list still being updated?

### ISSUE THREAD

**Issue by thac-01** [Lennolium/PrivacyShield#14]
<div align="center">  
  <img width="247" height="100" src="https://github.com/Lennolium/PrivacyShield/blob/main/Logos/Logo.png?raw=true" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist (Bronze, Silver, ...?)
- [ ] App Broken
- [ ] Website Broken
- [ ] Image(s) not showing
- [x] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail:  
This list has never been updated since it was published.
Is it no longer maintained?

**Comment by Lennolium** [comment]
Yes of course. Right now I am really focusing on pushing a huge update for PrivacyShield. So thats why it takes such a long time. I am trying to implement an automatic check for false positives with ML and auto-updating the lists. 
I am sorry for letting you wait that long, but I can ensure, that the Lists are still maintained.

**Comment by sergeevabc** [comment]
@Lennolium, it's been a year and a half, what's the news?

**Comment by Lennolium** [comment]
@sergeevabc 
I finished all domain aggregation for block and white lists. I just need to compile them now. You can expect the update in a few days. From that on I will implement a CI pipeline so the lists will be updated each week automatically :)

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by Lennolium** [comment]
> Err… Hello?

Most lists (bronze - platinum) got updated to v2.0.0. For diamond and antimatter the compile time takes a lot more time. Do you have another request/issue I could help you with? :)
