### ISSUE TITLE
PrivacyShield list breaks TikTok

### ISSUE THREAD

**Issue by jferris-** [Lennolium/PrivacyShield#15]
I'm using the Platinum list and have found this completely breaks TikTok. No videos load whatsoever, neither do the thumbnails or profile pictures. 

To your knowledge, of the many addresses/urls TikTok reaches out to, do you know which ones I can whitelist, please?

Whitelisting 'tiktokv.com' fixes the issue of the thumbnails and profile pictures only.

**Comment by Lennolium** [comment]
This is expected behavior, because Tik Tok in general is a big spy company. I think about maybe creating a separate list with all social media not blocked :)
