### ISSUE TITLE
fishshell.com is blocked 

### ISSUE THREAD

**Issue by J3m5** [Lennolium/PrivacyShield#18]
<div align="center">  
  <img width="247" height="100" src="https://github.com/Lennolium/PrivacyShield/blob/master/Logos/Logo.png?raw=true" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>

### Issue:

- [ ] Whitelist
- [x] Blacklist (Platinium)
- [ ] App Broken
- [ ] Website Broken
- [ ] Image(s) not showing
- [ ] Request
- [ ] Other Issue

<hr>

### Domain:

```
 185.199.110.153 (fishshell.com)
```

<hr>

### Details:

The ip of the fishshell website is blocked by the Platinium list.

**Comment by Lennolium** [comment]
Fixed in upcoming update. Thanks for your patience! 🥳
