### ISSUE TITLE
myprotein.es is blocked

### ISSUE THREAD

**Issue by Javiito32** [Lennolium/PrivacyShield#20]
<div align="center">  
  <img width="247" height="100" src="https://github.com/Lennolium/PrivacyShield/blob/master/Logos/Logo.png?raw=true" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
- [ ] Whitelist
- [x] Blacklist (Gold)
- [ ] App Broken
- [ ] Website Broken
- [ ] Image(s) not showing
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):
```
myprotein.es
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail:

**Comment by Lennolium** [comment]
Fixed in upcoming update. Thanks for your patience! 🥳
