### ISSUE TITLE
fix app.gitbook.io

### ISSUE THREAD

**Issue by malikshi** [Lennolium/PrivacyShield#5]
<div align="center">  
  <img width="247" height="100" src="https://github.com/Lennolium/PrivacyShield/raw/main/Logo.png" alt="logo" />
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help me to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Image(s) not showing
- [ ] Request
- [ ] Other Issue

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send me the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
||app.gitbook.com^
```

<hr>

### Details:
You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
 websites broken dropdown menu and assets woff cannot be accessed.
![image](https://user-images.githubusercontent.com/9080737/157336659-b7f72a92-b130-47e3-a9af-306c98c30d5f.png)

try accessing https://lancellc.gitbook.io/clash/

**Comment by Lennolium** [comment]
Fixed!

**Comment by malikshi** [comment]
thanks you

**Comment by Dynasty-Dev** [comment]
thanks @Lennolium
